if (!window.__HEALTHIA_COST_CONTROL__) {
  window.__HEALTHIA_COST_CONTROL__ = true;
(() => {
  const $=(selector,root=document)=>root.querySelector(selector),i18n=window.HealthIAI18n,text=(en,es)=>i18n?.locale==="es"?es:en;let status=null;
  function ensureStylesheet(){if($('link[data-cost-control-style]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='/assets/cost-control.css';link.dataset.costControlStyle='true';document.head.append(link);}
  function ensureUi(){const actions=$('.topbar-actions');if(!actions)return;if(!$('#costGuardButton')){const button=document.createElement('button');button.id='costGuardButton';button.type='button';button.className='cost-guard-pill';button.addEventListener('click',openDialog);actions.prepend(button);}$('#costGuardDialog')?.remove();const dialog=document.createElement('dialog');dialog.id='costGuardDialog';dialog.className='cost-guard-dialog';dialog.innerHTML=`<form method="dialog" class="cost-guard-card"><header><div><small>${text("SPEND CONTROL","CONTROL DE CONSUMO")}</small><h2>${text("Google AI under a hard guard","Google AI bajo llave")}</h2></div><button class="cost-close" value="cancel" aria-label="${text("Close","Cerrar")}">×</button></header><section class="cost-state"><div><span>${text("Mode","Modo")}</span><strong id="costMode">—</strong></div><div><span>${text("Requests used","Solicitudes usadas")}</span><strong id="costUsed">—</strong></div><div><span>${text("Remaining","Restantes")}</span><strong id="costRemaining">—</strong></div><div><span>${text("Max output","Salida máxima")}</span><strong id="costTokens">—</strong></div></section><label class="cost-switch-row"><div><strong>${text("Allow Google AI calls","Permitir llamadas a Google AI")}</strong><small id="costSwitchHelp">${text("Local mode makes no billable calls.","El modo local no genera llamadas facturables.")}</small></div><span class="cost-switch"><input id="costGuardToggle" type="checkbox"><i></i></span></label><p id="costTruth" class="cost-truth"></p><div class="cost-actions"><button id="costRefresh" type="button">${text("Refresh","Actualizar")}</button><button id="costProbe" type="button" class="primary">${text("Test 1 request","Probar 1 solicitud")}</button></div><p id="costFeedback" class="cost-feedback" role="status"></p></form>`;document.body.append(dialog);$('#costGuardToggle',dialog).addEventListener('change',event=>setEnabled(event.target.checked));$('#costRefresh',dialog).addEventListener('click',loadStatus);$('#costProbe',dialog).addEventListener('click',runProbe);}
  const modeLabel=value=>({local:text('Safe local','Local seguro'),guarded:text('Guarded test','Prueba controlada'),cloud_demo:text('Cloud demo','Demo Cloud')})[value]||value||text('Unknown','Desconocido');
  const googleAiConfigured=()=>Boolean(status?.google_ai_configured),isVertex=()=>status?.ai_transport==='vertex_ai';
  function renderRuntimeLabel(){const label=$('#runtimeLabel');if(!label||!status)return;if(status.mode==='local'){label.textContent=text('Local mode · zero calls','Modo local · cero llamadas');label.dataset.aiState='off';label.title=text('Deterministic flows work without spending Google AI.','Los flujos deterministas funcionan sin consumir Google AI.');return;}if(!googleAiConfigured()){label.textContent=isVertex()?text('Vertex AI · unavailable','Vertex AI · no disponible'):text('Gemini · not configured','Gemini · no configurado');label.dataset.aiState='error';return;}if(status.mode==='cloud_demo'&&isVertex()){label.textContent=status.enabled?`${status.model} · ${text('Vertex AI active','Vertex AI activo')}`:`${status.model} · ${text('Cloud limit reached','límite Cloud alcanzado')}`;label.dataset.aiState=status.enabled?'ready':'configured';label.title=status.enabled?text(`Vertex AI uses service identity. ${status.requests_remaining} requests remain in this revision.`,`Vertex AI usa identidad de servicio. Quedan ${status.requests_remaining} solicitudes en esta revisión.`):text('The revision request ceiling blocks additional calls.','El límite duro de esta revisión bloquea llamadas adicionales.');return;}label.textContent=status.enabled?`${status.model} · ${text('controlled AI active','IA controlada activa')}`:`${status.model} · ${text('controlled AI off','IA controlada apagada')}`;label.dataset.aiState=status.enabled?'ready':'configured';}
  function render(){ensureUi();if(!status)return;const pill=$('#costGuardButton'),remaining=Number(status.requests_remaining||0),configured=googleAiConfigured();pill.dataset.enabled=String(Boolean(status.enabled));pill.dataset.mode=status.mode||'local';pill.textContent=status.mode==='local'?text('Local · 0 calls','Local · 0 llamadas'):status.mode==='cloud_demo'&&isVertex()?(status.enabled?`Vertex · ${remaining} ${text('remaining','restantes')}`:`Vertex · ${text('limit','límite')} ${remaining}`):(status.enabled?`${text('AI active','IA activa')} · ${remaining} ${text('remaining','restantes')}`:`${text('AI off','IA apagada')} · ${remaining} ${text('remaining','restantes')}`);pill.title=text('Open Google AI spend control','Abrir control de consumo de Google AI');renderRuntimeLabel();$('#costMode').textContent=modeLabel(status.mode);$('#costUsed').textContent=`${status.requests_used||0} / ${status.request_limit||0}`;$('#costRemaining').textContent=String(remaining);$('#costTokens').textContent=`${status.max_output_tokens||0} tokens`;$('#costTruth').textContent=status.truth_boundary||'';const toggle=$('#costGuardToggle');toggle.checked=Boolean(status.enabled);toggle.disabled=!status.mutable||!configured||!status.ui_control_available||remaining<=0;$('#costSwitchHelp').textContent=status.mode==='local'?text('Restart with guarded AI to enable a bounded local test.','Reinicia con IA controlada para habilitar una prueba local acotada.'):!configured?text('Google AI is unavailable in this process.','Google AI no está disponible en este proceso.'):status.mode==='cloud_demo'&&isVertex()?text('Cloud uses Vertex AI service identity; the request ceiling is fixed at deployment.','Cloud usa identidad de servicio de Vertex AI; el límite se fija al desplegar.'):status.mutable?text('You can disable it at any time; the ceiling turns it off automatically.','Puedes apagarlo en cualquier momento; el límite lo apaga automáticamente.'):text('This mode is fixed at process startup.','El modo se fija al iniciar.');$('#costProbe').disabled=!status.enabled||remaining<=0;}
  async function requestJson(url,options={}){const headers=new Headers(options.headers||{});headers.set('Accept-Language',i18n?.locale||'en');const response=await fetch(url,{...options,headers});let payload={};try{payload=await response.json();}catch{}if(!response.ok)throw new Error(payload.detail||`Error ${response.status}`);return payload;}
  async function loadStatus(){try{status=await requestJson('/api/cost-control');render();const feedback=$('#costFeedback');if(feedback)feedback.textContent='';}catch(error){const feedback=$('#costFeedback');if(feedback)feedback.textContent=error.message;}}
  async function setEnabled(enabled){const toggle=$('#costGuardToggle');toggle.disabled=true;try{status=await requestJson(`/api/cost-control?enabled=${enabled?'true':'false'}`,{method:'POST'});$('#costFeedback').textContent=enabled?text('Google AI enabled within this process ceiling.','Google AI activado dentro del límite de esta ejecución.'):text('Google AI disabled; deterministic flows continue.','Google AI apagado; el flujo determinista continúa.');}catch(error){$('#costFeedback').textContent=error.message;await loadStatus();}render();}
  async function runProbe(){const button=$('#costProbe');button.disabled=true;$('#costFeedback').textContent=text('Running one real request and charging it against the ceiling…','Ejecutando una solicitud real y descontándola del límite…');try{const result=await requestJson('/api/ai/test',{method:'POST'});$('#costFeedback').textContent=result.ok?text('Test completed and counted.','Prueba completada y contabilizada.'):`${text('Test not completed','Prueba no completada')}: ${result.detail||result.status}`;}catch(error){$('#costFeedback').textContent=error.message;}await loadStatus();}
  async function openDialog(){ensureUi();await loadStatus();$('#costGuardDialog')?.showModal();}
  async function boot(){ensureStylesheet();ensureUi();await loadStatus();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();document.addEventListener('healthia:ui-updated',()=>setTimeout(loadStatus,80));document.addEventListener('healthia:locale-changed',()=>{ensureUi();render();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadStatus();});window.addEventListener('focus',loadStatus);window.HealthIACostControl={refresh:loadStatus};
})();
}